// RESET STATE
export const RESET_REQUEST_AUTH = 'RESET_REQUEST_AUTH';
export const RESET_REQUEST_COMPLAINTS = 'RESET_REQUEST_COMPLAINTS';
export const RESET_REQUEST_OWNERS = 'RESET_REQUEST_OWNERS';
export const RESET_REQUEST_BARCODES = 'RESET_REQUEST_BARCODES';

// AUTH LOGIN
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';

// AUTH LOGOUT 
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const REQUEST_LOGOUT_SUCCESS = 'REQUEST_LOGOUT_SUCCESS';
export const REQUEST_LOGOUT_FAILED = 'REQUEST_LOGOUT_FAILED';

// Lists Complaints
export const REQUEST_COMPLAINTS = 'REQUEST_COMPLAINTS';
export const REQUEST_COMPLAINTS_SUCCESS = 'REQUEST_COMPLAINTS_SUCCESS';
export const REQUEST_COMPLAINTS_FAILED = 'REQUEST_COMPLAINTS_FAILED';

// Detail Complaints
export const REQUEST_DETAIL_COMPLAINT = 'REQUEST_DETAIL_COMPLAINT';
export const REQUEST_DETAIL_COMPLAINT_SUCCESS = 'REQUEST_DETAIL_COMPLAINT_SUCCESS';
export const REQUEST_DETAIL_COMPLAINT_FAILED = 'REQUEST_DETAIL_COMPLAINT_FAILED';

// Add Complaints
export const REQUEST_ADD_COMPLAINT = 'REQUEST_ADD_COMPLAINT';
export const REQUEST_ADD_COMPLAINT_SUCCESS = 'REQUEST_ADD_COMPLAINT_SUCCESS';
export const REQUEST_ADD_COMPLAINT_FAILED = 'REQUEST_ADD_COMPLAINT_FAILED';

// Edit Complaints
export const REQUEST_EDIT_COMPLAINT = 'REQUEST_EDIT_COMPLAINT';
export const REQUEST_EDIT_COMPLAINT_SUCCESS = 'REQUEST_EDIT_COMPLAINT_SUCCESS';
export const REQUEST_EDIT_COMPLAINT_FAILED = 'REQUEST_EDIT_COMPLAINT_FAILED'

// Owner
export const REQUEST_GET_OWNERS = 'REQUEST_GET_OWNERS';
export const REQUEST_GET_OWNERS_SUCCESS = 'REQUEST_GET_OWNERS_SUCCESS';
export const REQUEST_GET_OWNERS_FAILED = 'REQUEST_GET_OWNERS_FAILED';

// Barcode
export const REQUEST_GET_BARCODES = 'REQUEST_GET_BARCODES';
export const REQUEST_GET_BARCODES_SUCCESS = 'REQUEST_GET_BARCODES_SUCCESS';
export const REQUEST_GET_BARCODES_FAILED = 'REQUEST_GET_BARCODES_FAILED';
