export const RESET_AUTH_REQUEST = 'RESET_AUTH_REQUEST';
export const RESET_COMPLAINTS_REQUEST = 'RESET_COMPLAINTS_REQUEST';

// AUTH LOGIN
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED';

// AUTH LOGOUT 
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const REQUEST_LOGOUT_SUCCESS = 'REQUEST_LOGOUT_SUCCESS';
export const REQUEST_LOGOUT_FAILED = 'REQUEST_LOGOUT_FAILED';

// Lists Complaints
export const REQUEST_COMPLAINTS = 'REQUEST_COMPLAINTS';
export const REQUEST_COMPLAINTS_SUCCESS = 'REQUEST_COMPLAINTS_SUCCESS';
export const REQUEST_COMPLAINTS_FAILED = 'REQUEST_COMPLAINTS_FAILED';

// Detail Complaints
export const REQUEST_DETAIL_COMPLAINT = 'REQUEST_DETAIL_COMPLAINT';
export const REQUEST_DETAIL_COMPLAINT_SUCCESS = 'REQUEST_DETAIL_COMPLAINT_SUCCESS';
export const REQUEST_DETAIL_COMPLAINT_FAILED = 'REQUEST_DETAIL_COMPLAINT_FAILED';

// Add Complaints
export const REQUEST_ADD_COMPLAINT = 'REQUEST_ADD_COMPLAINT';
export const REQUEST_ADD_COMPLAINT_SUCCESS = 'REQUEST_ADD_COMPLAINT_SUCCESS';
export const REQUEST_ADD_COMPLAINT_FAILED = 'REQUEST_ADD_COMPLAINT_FAILED';

// Edit Complaints
export const REQUEST_EDIT_COMPLAINT = 'REQUEST_EDIT_COMPLAINT';
export const REQUEST_EDIT_COMPLAINT_SUCCESS = 'REQUEST_EDIT_COMPLAINT_SUCCESS';
export const REQUEST_EDIT_COMPLAINT_FAILED = 'REQUEST_EDIT_COMPLAINT_FAILED'
